version: '3.8'

services:
  nca-client:
    build: .
    ports:
      - "8081:80"
    env_file:
      - .env
    volumes:
      - ./config.php:/var/www/html/config.php
      - ./api:/var/www/html/api
      - ./css:/var/www/html/css
      - ./js:/var/www/html/js
      - ./temp:/var/www/html/temp
      - ./index.php:/var/www/html/index.php
      - ./test_files:/var/www/html/test_files